name: Go - Devops-Ninja

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  test:
    name: Teste go - Devops-Ninja
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go v3
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Build
      run: |
          pwd
          ls -lah
          go install github.com/golang/mock/mockgen@v1.6.0
          go install github.com/jstemmer/go-junit-report@latest
          go generate ./...
          go build -v ./...

    - name: Teste go
      run: go test -v ./...